### ISSUE TITLE
Support company proxy

### ISSUE THREAD

**Issue by nzerr** [wassim-k/sp-entity#4]
The CLI tool does not support company proxy, thus it blocks all requests made to SharePoint API. 

A suggestion would be to implement a custom implementation of NodeFetchClient by retrieving the proxy settings from the environment then use an http proxy agent. The may are better options though.

This would be something like :

```typescript
export class NodeFetchClientWithProxy extends NodeFetchClient {
    constructor(parameters: IAuthOptions) {
        super(parameters);
    }

    public fetch(url: string, options: FetchOptions): Promise<any> {

        const optionsWithProxyAgent: any = options;

        if (process.env.HTTPS_PROXY || process.env.HTTP_PROXY) {
            optionsWithProxyAgent.agent = new ProxyAgent(process.env.HTTPS_PROXY || process.env.HTTP_PROXY);
        }

        return super.fetch(url, optionsWithProxyAgent || options);
    }
}
```

**Comment by wassim-k** [comment]
Again, thanks for suggesting a fix, that seems good to me, except I'd suggest adding proxy settings to `spe.config.json` since it's already used as single source of configuration.
Are you able to raise a PR for this?
